# Fly.io configuration for the frontend (React static via serve)

app = "movie-search-ai-frontend"

[build]
  # Uses the Dockerfile in this directory

[env]
  # Expose the API base URL for the frontend build
  REACT_APP_API_URL = "https://movie-search-ai-backend.fly.dev/api"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1


