services:
  - type: web
    name: movie-search-backend
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://YOUR-NETLIFY-SITE.netlify.app
    healthCheckPath: /api/regional-industries
  - type: static_site
    name: movie-search-frontend
    plan: free
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    pullRequestPreviewsEnabled: false
    envVars:
      - key: REACT_APP_API_URL
        sync: false
