# Fly.io configuration for the backend (Spring Boot)

app = "movie-search-ai-backend"

[build]
  # Uses the Dockerfile in this directory

[env]
  # Fly will inject PORT. Spring Boot reads server.port from env PORT already.
  JAVA_OPTS = "-XX:MaxRAMPercentage=75.0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1


